### PR TITLE
Switch from Teaspoon to Jasmine

### PR DESCRIPTION
**Pull request by colinbruce**
Removed teaspoon and switched to minimal implementation of jasmine

### CODE REVIEW

**Comment by dotemacs** [comment]
With this change will all the tests run as before with `bundle exec rake jasmine:ci`?

If yes, then go ahead.

**Comment by novotnyjakub** [comment]
I'm trying to understand what's the change / benefit in doing this? Is Teaspoon just a runner for Jasmine tests anyway?

**Comment by colinbruce** [comment]
Teaspoon was a layer on top of jasmine that wasn't liked or needed!

I started pulling teaspoon out before the pegging of sprockets stopped the post Rails update errors.

I thought I might as well push it!

**Comment by novotnyjakub** [comment]
Cool, if it's removing an unnecessary layer, go ahead!

**Pull request merged**
