### PR TITLE
Front-end changes

### PR DESCRIPTION
**Pull request by colinbruce**
Consolidated front-end changes
* Added the date hint text
* Deleted the Hint text spans from the page
* Updated the yml file to add _html suffix to the optional
label, this removes need from putting html safe on view
* removed span.hint css
* updated the date hint text to point at the correct label

### CODE REVIEW

**Comment by colinbruce** [comment]
@kelliematheson /@leighmoney With the [hint text ticket](https://www.pivotaltracker.com/story/show/106632440), was there a particular date we should show?

**Comment by kelliematheson** [comment]
@colinbruce The copy to use is in the ticket already, the grey hint text should have this exact whole line of copy:

For example DD/MM/YYYY

So it will look like this:

Date of birth
For example DD/MM/YYYY
[                                  ]

**Comment by colinbruce** [comment]
@kelliematheson Ready for testing on https://front-end-combined.helpwithcourtfees.dsd.io/

**Comment by kelliematheson** [comment]
Tested on branch builder and approve

**Pull request merged**
