### PR TITLE
Refactor to form objects

### PR DESCRIPTION
**Pull request by dotemacs**
It started of as the first step towards refactoring all the pages so that they use form objects.

But we've added the refactoring of the **ApplicationDetail** which holds the second page **application_details**. 

And we decided to use this branch as the home for all the subsequent changes.

:octocat: :syringe: :eyes:

### CODE REVIEW

**Comment by colinbruce** [comment]
Looks good :+1:

**Comment by colinbruce** [comment]
Looks better! :checkered_flag:

**Comment by dotemacs** [comment]
@novotnyjakub can you please have a look at this when you get a minute? Thanks

**Comment by dotemacs** [comment]
@colinbruce oh, and there is only **one** failing test :bangbang:

**Comment by dotemacs** [comment]
@colinbruce 

I think that this is the problematic part:
https://github.com/ministryofjustice/fr-staffapp/blob/personal-details-refactor/app/controllers/applications/build_controller.rb#L36-L37

The controller should redirect after `@application.savings_investment_valid?` but looking at **savings_investment_valid?**: 
https://github.com/ministryofjustice/fr-staffapp/blob/personal-details-refactor/app/models/application.rb#L132-L139 it seems to me that this is where we have to have a better look.

**Comment by colinbruce** [comment]
@dotemacs This can be squashed too at some point, but the setting on the page was wrong.

The tests, and validation, now pass :question: :exclamation:

**Comment by dotemacs** [comment]
@colinbruce oh, the reason for failures is RuboCop violations! Great:)

**Comment by colinbruce** [comment]
Looks good and tests passing... go, go, go.

**Pull request merged**
