### PR TITLE
Outofbox frontend

### PR DESCRIPTION
**Pull request by Demwunz**
Changes for the Out of box experience, lots of broken tests somehow

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 447240b45f85ea71a3cdc1cbf68e589c11890db4
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 447240b45f85ea71a3cdc1cbf68e589c11890db4
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 447240b45f85ea71a3cdc1cbf68e589c11890db4
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 447240b45f85ea71a3cdc1cbf68e589c11890db4
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by colinbruce** [comment]
Closed as this work was moved into another branch and merged from there

**Pull request closed without merging**
