### PR TITLE
Staff guide updates

### PR DESCRIPTION
**Pull request by leighmoney**
Changes to processing applications waiting  for part-payment and evidence

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ab387bb7ab75f8fa71d5259115983dd6896edf55
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by leighmoney** [comment]
@colinbruce - some tests are failing on this as I changed some link copy - could you fix when you get the chance pls? Thank you.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ab387bb7ab75f8fa71d5259115983dd6896edf55
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by colinbruce** [comment]
Checked, fixed, merging :+1:

**Pull request merged**
