### PR TITLE
Update Benefit check styling

### PR DESCRIPTION
**Pull request by colinbruce**
Set styling of the benefit checker

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e40ad81f9c92d687912ec37269c86c44ae1f63ed
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e40ad81f9c92d687912ec37269c86c44ae1f63ed
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e40ad81f9c92d687912ec37269c86c44ae1f63ed
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by kelliematheson** [comment]
Reviewed on demo env, all changes make and acceptable. Please merge

**Pull request merged**
