### PR TITLE
Re-refactor application_detail

### PR DESCRIPTION
**Pull request by colinbruce**
Following this morning's quick reversion of the previous refactoring 
code, this is another attempt at refactoring the application detail to 
remove the duplication.

Interested to discuss the pros and cons of the following
* 3.months.ago vs Time.zone.today - 3.months
* TIME_LIMIT_FOR_PROBATE.years.ago vs
 Time.zone.today - TIME_LIMIT_FOR_PROBATE.years

### CODE REVIEW

**Comment by novotnyjakub** [comment]
I'm thinking, considering the bug yesterday, which our tests didn't pick up. We should probably have some tests around this, probably using timecop so that we can freeze time for a particular date and then test the variants. The problem is that our tests use `Time.today`, so they always pass.

**Comment by colinbruce** [comment]
@novotnyjakub Like this? 
https://github.com/ministryofjustice/fr-staffapp/blob/master/spec/models/applikation/forms/application_detail_spec.rb#L330  I added one this morning on the reversion to make sure that I was reverting it properly!

**Comment by novotnyjakub** [comment]
I meant more in the `describe 'validations' do` section, for each individual test. To freeze date for ie. `10/10/2015` and then test that `11/07/2015` is valid, `10/07/2015` invalid, etc. Because using `Time.zone.now - 3.months` is essentially the code, which means the is testing the implementation, rather than the conditions. 

Hope that makes sense.

**Comment by colinbruce** [comment]
Okay, I see what you mean.

**Comment by colinbruce** [comment]
@novotnyjakub can you re-review? Thanks.

**Pull request merged**
