### PR TITLE
Return 404 instead of 500

### PR DESCRIPTION
**Pull request by dotemacs**
When the user tries to look up some made up DWP check, it would return an error with 500 status code. Which means that the app would actually take the invalid input and do a database query with it. Which is not what we want.

This change prevents that by only allowing the valid format of the DWP check reference to be looked up.

### CODE REVIEW

**Comment by dotemacs** [comment]
@mattmb in the response I'm returning 'public/404.html' page. But I remember that you've created a controller which would generate the error pages that are meant to be served from S3. It would be good if those error pages and the ones I'm referencing here (i.e. 'public/*.html' pages) are in sync.

**Comment by mattmb** [comment]
I think you can just do: `render :status => 404` and rails will take care of the rest.

**Comment by dotemacs** [comment]
@mattmb re-implemented the way the DWP checks were being looked up. So we don't have to worry about it, as it'll raise a exception which will serve up the 404 response.

**Comment by mattmb** [comment]
LGTM :+1:

**Pull request merged**
