### PR TITLE
Dockerize the app

### PR DESCRIPTION
**Pull request by mattmb**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 98489d9aea4f3a1bad538d5ed7a2d79c31f2fa49
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 98489d9aea4f3a1bad538d5ed7a2d79c31f2fa49
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by mattmb** [comment]
@dotemacs can you check this over, I don't know the full history of this branch...

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 98489d9aea4f3a1bad538d5ed7a2d79c31f2fa49
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by dotemacs** [comment]
Theres  a lot going on here that's not strictly related. Can this be cleaned up before it gets merged. Thanks

**Comment by colinbruce** [comment]
I'm working on separate branches for functionality that ended up included in here

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 98489d9aea4f3a1bad538d5ed7a2d79c31f2fa49
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Pull request closed without merging**
