### PR TITLE
Using 'rake db:schema:load' for TravisCI

### PR DESCRIPTION
**Pull request by dotemacs**
Since Rails 4.1 this line in rails_helper:

    ActiveRecord::Migration.maintain_test_schema!

checks if there are any pending migrations and complains if there are.

Otherwise just load the schema.

### CODE REVIEW

**Comment by dotemacs** [comment]
@mattmb What version of PostgreSQL are we using? I ask because in the TravisCI config we have **9.3** specified. Is there anything specific that needs to be pinned at this version or can we 'upgrade' the config to **9.4**? Thanks

**Comment by mattmb** [comment]
9.3.5

We're limited to what RDS provides. It should auto update the minor version but won't bump to 9.4 until RDS release that version and we rebuild our stacks.

**Comment by novotnyjakub** [comment]
RDS does provide `9.4`, we've used it for sure on other project.

**Comment by novotnyjakub** [comment]
:+1:

**Pull request merged**
