### PR TITLE
Updated copy on evidence check bullets

### PR DESCRIPTION
**Pull request by colinbruce**
Removed evidence check bullets

### CODE REVIEW

**Comment by colinbruce** [comment]
@kelliematheson Can you check this at https://evidence-check-bullets-lm.helpwithcourtfees.dsd.io/ 

I'm not sure what ticket it addresses in pivotal.

**Comment by colinbruce** [comment]
@kelliematheson I found the ticket, but it seems to be closed? https://www.pivotaltracker.com/story/show/107031092

**Comment by kelliematheson** [comment]
Thanks for reopening it @colinbruce I think Adrian went a little accept crazy.

**Comment by colinbruce** [comment]
@kelliematheson No comment! ;-)

**Comment by kelliematheson** [comment]
Tested on Branchbuilder, the last task in the description has not been done:
"Remove bullets on right-hand guidance and change copy to match prototype."

https://www.pivotaltracker.com/story/show/107031092

**Comment by kelliematheson** [comment]
Tested on Branchbuilder and accept

**Pull request merged**
