### PR TITLE
Implemented graphs per office

### PR DESCRIPTION
**Pull request by dotemacs**
With the changes introduced, graphs will be displayed per office rather
than across the whole service, for the week gone.

### CODE REVIEW

**Comment by colinbruce** [comment]
Apart from the rubocop it looks fine!

**Comment by dotemacs** [comment]
I'm aware of the broken spec, fixing it now!

**Comment by colinbruce** [comment]
Looks good :+1:

**Comment by dotemacs** [comment]
Merging now.

**Pull request merged**
