### PR TITLE
Updated date hint text, and emergency error messages

### PR DESCRIPTION
**Pull request by kelliematheson**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c1d674752aa64f644fbd6bbc45876728492ee319
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c1d674752aa64f644fbd6bbc45876728492ee319
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c1d674752aa64f644fbd6bbc45876728492ee319
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3fea0f18f9bfd88fbf33fbce3aad020f72d8cdfd
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by colinbruce** [comment]
Looks good, merging...

**Pull request merged**
