### PR TITLE
Add optional field to title

### PR DESCRIPTION
**Pull request by kelliematheson**
So that users can tell what fields are optional.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e90681c70263e78409e5adebefc22692c6418608
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e90681c70263e78409e5adebefc22692c6418608
  * Your subject line is longer than 50 characters

 * Commit: 6b60408593a50ad9d5c2cd830c2a0d48b3046c13
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e90681c70263e78409e5adebefc22692c6418608
  * Your subject line is longer than 50 characters

 * Commit: 6b60408593a50ad9d5c2cd830c2a0d48b3046c13
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by colinbruce** [comment]
Looks good.  Merge at will

**Pull request merged**
