### PR TITLE
Reference number

### PR DESCRIPTION
**Pull request by dotemacs**
Implemented reference number creation for the application.

Pivotal tickets:
https://www.pivotaltracker.com/story/show/93435558

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: db6b79b0571b9162297caf8bcefe342510d9edad
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Comment by colinbruce** [comment]
What is the plan for adding BE codes to existing systems after merge?
Other than that, and the year issue(!), looks good, merge when happy!

**Comment by dotemacs** [comment]
@colinbruce I just wanted to get this out there. But you're right, the business entity codes (**BEC**) should be added. The way I've setup the **Office** model, **entity_code** attribute is mandatory:

https://github.com/ministryofjustice/fr-staffapp/pull/256/files#diff-eadb104209ceb5ae94ea99dfa3d4a8ebR10

so when an Admin adds an Office, they'll have to add it at that point. 

If this 'flow' doesn't work, or if there is a better way of doing it, let me know...

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: be55a82e3b2f73ad40b9bcddf5d5d12fc92db210
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/ministryofjustice/fr-staffapp

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
