### PR TITLE
Upgrade Ruby version and gems

### PR DESCRIPTION
**Pull request by dotemacs**
Upgraded Ruby from 2.1.5 to 2.2.1 and all the outdated gems.

### CODE REVIEW

**Comment by colinbruce** [comment]
Looks good :+1:

**Comment by dotemacs** [comment]
@colinbruce it looks like the build passed, at list for the 'continuous-integration/travis-ci/push' part of the build. Travis lies when it says that it can't find **.ruby-version**.

**Comment by dotemacs** [comment]
@colinbruce Why do we have two builds running on Travis? Thanks

**Comment by colinbruce** [comment]
@dotemacs I'll need to research why travis 'couldn't find it' because it obviously did!

The two builds are one for the push, and one for the pull request as a whole.  Apparently they always did this, but recent changes to the github hooks allow them to show both. 

Other than that, :+1: for the pull request.

**Pull request closed without merging**
