### PR TITLE
Branchrunnertest

### PR DESCRIPTION
**Pull request by filipposc5**
Just testing ignore

### CODE REVIEW

**Comment by dotemacs** [comment]
@filipposc5 do we need to keep this PR around? No rush in replying. Thanks

**Comment by filipposc5** [comment]
maybe we can test the 'retest' funcitonality tomorrow. Keep it and I will
delete tomorrow.

**Comment by filipposc5** [comment]
retest this please

**Comment by dotemacs** [comment]
Only used for testing branch-runner on Jenkins...

No longer needed, closing

**Pull request closed without merging**
