### PR TITLE
Deleted applications

### PR DESCRIPTION
**Pull request by novotnyjakub**
User can mark application as deleted from the detail of processed application. They have to provide a reason for the deletion. 

Deleted applications are then displayed in the new section, which has almost identical behaviour to processed applications.

### CODE REVIEW

**Comment by colinbruce** [comment]
Do we need the app/controllers/concerns/.keep file?

**Comment by novotnyjakub** [comment]
No, that's why I removed it ;-)

**Comment by novotnyjakub** [comment]
I've implemented the missing bit which was adding audit data `deleted_at` and `deleted_by`. The problem with the solution is that if we carry on with the approach we'd have a pair of columns for each state, to track who and when did it. Maybe we should consider using another solution for this, but for now to move on, it's implemented like this.

**Comment by novotnyjakub** [comment]
With the codeclimate check, I don't think I can do something about it now. The reason for this is that we're delegating a lot of methods to the split models. That work has never been fully completed so until that's done, I guess we'll have to live with it.

This issue doesn't actually decrease the GPA, so I wouldn't worry about it too much.

**Comment by colinbruce** [comment]
Agreed on the codeclimate point. 

LGTM, merge when ready. :+1:

**Pull request merged**
